spring:
    # data:
    #     jpa:
    #         repositories:
    #             bootstrap-mode: default
    datasource:
        url: jdbc:h2:file:/data/demo
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                hbm2ddl:
                    import_files: '[/database/data/*.sql]' # pour Hibernate
    sql:
        init:
            data-locations: classpath:database/data/*.sql # pour JDBC
            schema-locations: classpath:database/schema/*.sql
