spring:
    # data:
    #     jpa:
    #         repositories:
    #             bootstrap-mode: default
    datasource:
        url: jdbc:h2:mem:testdb #jdbc:h2:file:/data/demo
        username: sa
        password: 
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        # defer-datasource-initialization: true
        hibernate:
                ddl-auto: none
                # import_files: '[classpath:database/data/brands.sql]' # pour Hibernate
    sql:
        init:
            # mode: always
            data-locations: classpath:database/data.sql # pour JDBC
            schema-locations: classpath:database/schema.sql
springdoc:
    api-docs:
        enabled: true
        path: '/api/v1'
    swagger-ui:
        path: '/swagger-ui'
        config-url: '/api/v1/swagger-config'
        url: '/api/v1'
        doc-expansion: none
        disable-swagger-default-url: true
logging:
  level:
    org.hibernate.SQL: '[debug]'