server:
    port: 8080 # Default value: 8080
    error:
        include-message: always # Add message to HTTP error
    servlet:
        context-path: /api/v1 # Add relative path to all endpoints
spring:
    # data:
    #     jpa:
    #         repositories:
    #             bootstrap-mode: default
    datasource:
        url: jdbc:h2:mem:testdb #jdbc:h2:file:/data/demo
        username: sa
        password: 
        driverClassName: org.h2.Driver
    h2.console:
        enabled: true
    jpa:
        # defer-datasource-initialization: true
        hibernate:
                ddl-auto: update
                # import_files: '[classpath:database/data/brands.sql]' # pour Hibernate
        show-sql: true
    sql:
        init:
            # mode: always
            data-locations: classpath:database/data.sql # pour JDBC
            schema-locations: classpath:database/schema.sql
springdoc:
    api-docs:
        # enabled: true
        path: '/docs' # path we can find in search bar (and under definition)
        # http://localhost:8080/api/v1/swagger-ui/index.html
    # https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
    swagger-ui:
        # enabled: true
        url: '/docs'
        # doc-expansion: none # how controllers are expanded: list, full, none. Default value: list 
        # disable-swagger-default-url: true

# logging.level.org.hibernate.SQL: '[debug]'
logging.level:
    org:
        hibernate:
            sql: debug