spring:
    # data:
    #     jpa:
    #         repositories:
    #             bootstrap-mode: default
    datasource:
        url: jdbc:h2:mem:testdb #jdbc:h2:file:/data/demo
        username: sa
        password: 
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        properties:
            hibernate:
                hbm2ddl:
                    auto: create-drop
                    import_files: classpath:database/data/*.sql # pour Hibernate
    # sql:
    #     init:
    #         data-locations: classpath:database/data/factories.sql # pour JDBC
    #         schema-locations: classpath:database/schema/factories.sql
logging:
  level:
    org.hibernate.SQL: 'debug'